name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Install SSHX
        run: curl -sSf https://sshx.io/get | sh -s run
